$(document).ready(function(){
	$("#elvis").click(function(){
		$("#wrapperID").toggleClass("secondWrapper");
		$("#wrapperID").toggleClass("wrapper");
		$("#elvis").toggleClass("Hidden");
		$("#idd").toggleClass("Hidden");
		$("#elvis3").toggleClass("Hidden");
		$("#elvis2").toggleClass("Hidden");
		$("#description").toggleClass("Hidden");
		$("#roofjump").toggleClass("Hidden");
		$("#test").toggleClass("Hidden");
		$("#jump").toggleClass("Hidden");
		$("#iddd").toggleClass("Hidden");
	});
	$("#elvis3").click(function() {
		$("#wrapperID").toggleClass("thirdWrapper");
		$("#wrapperID").toggleClass("wrapper");
		$("#elvis").toggleClass("Hidden");
		$("#elvis2").toggleClass("Hidden");
		$("#description").toggleClass("Hidden");
		$("#roofjump").toggleClass("Hidden");
		$("#test").toggleClass("Hidden");
		$("#jump").toggleClass("Hidden");
		$("#iddd").toggleClass("Hidden");	
	});
	$("#elvis2").click(function() {
		$("#wrapperID").toggleClass("fWrapper");
		$("#wrapperID").toggleClass("wrapper");
		$("#elvis").toggleClass("Hidden");
		$("#description").toggleClass("Hidden");
		$("#test").toggleClass("Hidden");
		$("#jump").toggleClass("Hidden");
		$("#elvis3").toggleClass("Hidden");
		$("#iddd").toggleClass("Hidden");
	});
});